version: '3.4'

services:
  ndsf.webapi:
    image: ${DOCKER_REGISTRY-}ndsfwebapi
    build:
      context: .
      dockerfile: NDSF.WebAPI/Dockerfile

  ndsf.webapi-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "NDSF.WebApi", "-app-port", "80" ]
    depends_on:
      - ndsf.webapi
    network_mode: "service:ndsf.webapi"
